// This file is generated by omniidl (C++ backend) - omniORB_4_3. Do not edit.

#include "LogService.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

OMNI_MAYBE_UNUSED static const char* _0RL_library_version = omniORB_4_3;



void
LogService::Log::operator>>= (cdrStream &_n) const
{
  id >>= _n;
  _n.marshalString(niveau,0);
  _n.marshalString(message,0);

}

void
LogService::Log::operator<<= (cdrStream &_n)
{
  (::CORBA::Long&)id <<= _n;
  niveau = _n.unmarshalString(0);
  message = _n.unmarshalString(0);

}

LogService::inputLog_ptr LogService::inputLog_Helper::_nil() {
  return ::LogService::inputLog::_nil();
}

::CORBA::Boolean LogService::inputLog_Helper::is_nil(::LogService::inputLog_ptr p) {
  return ::CORBA::is_nil(p);

}

void LogService::inputLog_Helper::release(::LogService::inputLog_ptr p) {
  ::CORBA::release(p);
}

void LogService::inputLog_Helper::marshalObjRef(::LogService::inputLog_ptr obj, cdrStream& s) {
  ::LogService::inputLog::_marshalObjRef(obj, s);
}

LogService::inputLog_ptr LogService::inputLog_Helper::unmarshalObjRef(cdrStream& s) {
  return ::LogService::inputLog::_unmarshalObjRef(s);
}

void LogService::inputLog_Helper::duplicate(::LogService::inputLog_ptr obj) {
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
}

LogService::inputLog_ptr
LogService::inputLog::_duplicate(::LogService::inputLog_ptr obj)
{
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
  return obj;
}

LogService::inputLog_ptr
LogService::inputLog::_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


LogService::inputLog_ptr
LogService::inputLog::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

LogService::inputLog_ptr
LogService::inputLog::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_inputLog _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_inputLog* _the_nil_ptr = 0;
  if (!_the_nil_ptr) {
    omni::nilRefLock().lock();
    if (!_the_nil_ptr) {
      _the_nil_ptr = new _objref_inputLog;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* LogService::inputLog::_PD_repoId = "IDL:LogService/inputLog:1.0";


LogService::_objref_inputLog::~_objref_inputLog() {
  
}


LogService::_objref_inputLog::_objref_inputLog(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::LogService::inputLog::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
LogService::_objref_inputLog::_ptrToObjRef(const char* id)
{
  if (id == ::LogService::inputLog::_PD_repoId)
    return (::LogService::inputLog_ptr) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (::CORBA::Object_ptr) this;

  if (omni::strMatch(id, ::LogService::inputLog::_PD_repoId))
    return (::LogService::inputLog_ptr) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (::CORBA::Object_ptr) this;

  return 0;
}


//
// Code for LogService::inputLog::register

// Proxy call descriptor class. Mangled signature:
//  _cboolean_i_cLogService_mLog
class _0RL_cd_40489fd6a16fcad9_00000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_40489fd6a16fcad9_00000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  LogService::Log_var arg_0_;
  const LogService::Log* arg_0;
  ::CORBA::Boolean result;
};

void _0RL_cd_40489fd6a16fcad9_00000000::marshalArguments(cdrStream& _n)
{
  (const LogService::Log&) *arg_0 >>= _n;

}

void _0RL_cd_40489fd6a16fcad9_00000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = new LogService::Log;
  (LogService::Log&)arg_0_ <<= _n;
  arg_0 = &arg_0_.in();

}

void _0RL_cd_40489fd6a16fcad9_00000000::marshalReturnedValues(cdrStream& _n)
{
  _n.marshalBoolean(result);

}

void _0RL_cd_40489fd6a16fcad9_00000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = _n.unmarshalBoolean();

}

const char* const _0RL_cd_40489fd6a16fcad9_00000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_40489fd6a16fcad9_10000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_40489fd6a16fcad9_00000000* tcd = (_0RL_cd_40489fd6a16fcad9_00000000*)cd;
  LogService::_impl_inputLog* impl = (LogService::_impl_inputLog*) svnt->_ptrToInterface(LogService::inputLog::_PD_repoId);
  tcd->result = impl->_cxx_register(*tcd->arg_0);


}

::CORBA::Boolean LogService::_objref_inputLog::_cxx_register(const ::LogService::Log& gog)
{
  _0RL_cd_40489fd6a16fcad9_00000000 _call_desc(_0RL_lcfn_40489fd6a16fcad9_10000000, "register", 9);
  _call_desc.arg_0 = &(::LogService::Log&) gog;

  _invoke(_call_desc);
  return _call_desc.result;


}

LogService::_pof_inputLog::~_pof_inputLog() {}


omniObjRef*
LogService::_pof_inputLog::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::LogService::_objref_inputLog(ior, id);
}


::CORBA::Boolean
LogService::_pof_inputLog::is_a(const char* id) const
{
  if (omni::ptrStrMatch(id, ::LogService::inputLog::_PD_repoId))
    return 1;
  
  return 0;
}

const LogService::_pof_inputLog _the_pof_LogService_minputLog;

LogService::_impl_inputLog::~_impl_inputLog() {}


::CORBA::Boolean
LogService::_impl_inputLog::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if (omni::strMatch(op, "register")) {

    _0RL_cd_40489fd6a16fcad9_00000000 _call_desc(_0RL_lcfn_40489fd6a16fcad9_10000000, "register", 9, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
LogService::_impl_inputLog::_ptrToInterface(const char* id)
{
  if (id == ::LogService::inputLog::_PD_repoId)
    return (::LogService::_impl_inputLog*) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (void*) 1;

  if (omni::strMatch(id, ::LogService::inputLog::_PD_repoId))
    return (::LogService::_impl_inputLog*) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (void*) 1;
  return 0;
}

const char*
LogService::_impl_inputLog::_mostDerivedRepoId()
{
  return ::LogService::inputLog::_PD_repoId;
}

POA_LogService::inputLog::~inputLog() {}

