package LogService;

/**
* LogService/inputLogHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../Cpp/LogService.idl
* lundi 28 septembre 2026 03 h 38 EAT
*/

public final class inputLogHolder implements org.omg.CORBA.portable.Streamable
{
  public LogService.inputLog value = null;

  public inputLogHolder ()
  {
  }

  public inputLogHolder (LogService.inputLog initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = LogService.inputLogHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    LogService.inputLogHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return LogService.inputLogHelper.type ();
  }

}
