package LogService;


/**
* LogService/inputLogHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../Cpp/LogService.idl
* lundi 28 septembre 2026 03 h 38 EAT
*/

abstract public class inputLogHelper
{
  private static String  _id = "IDL:LogService/inputLog:1.0";

  public static void insert (org.omg.CORBA.Any a, LogService.inputLog that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static LogService.inputLog extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (LogService.inputLogHelper.id (), "inputLog");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static LogService.inputLog read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_inputLogStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, LogService.inputLog value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static LogService.inputLog narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof LogService.inputLog)
      return (LogService.inputLog)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      LogService._inputLogStub stub = new LogService._inputLogStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static LogService.inputLog unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof LogService.inputLog)
      return (LogService.inputLog)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      LogService._inputLogStub stub = new LogService._inputLogStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
