package LogService;


/**
* LogService/inputLog.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../Cpp/LogService.idl
* lundi 28 septembre 2026 03 h 38 EAT
*/

public interface inputLog extends inputLogOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface inputLog
