package LogService;


/**
* LogService/inputLogOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../Cpp/LogService.idl
* lundi 28 septembre 2026 03 h 38 EAT
*/

public interface inputLogOperations 
{
  boolean register (LogService.Log gog);
} // interface inputLogOperations
