package LogService;


/**
* LogService/Log.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../Cpp/LogService.idl
* lundi 28 septembre 2026 03 h 38 EAT
*/

public final class Log implements org.omg.CORBA.portable.IDLEntity
{
  public int id = (int)0;
  public String niveau = null;
  public String message = null;

  public Log ()
  {
  } // ctor

  public Log (int _id, String _niveau, String _message)
  {
    id = _id;
    niveau = _niveau;
    message = _message;
  } // ctor

} // class Log
