package LogService;

/**
* LogService/LogHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../Cpp/LogService.idl
* lundi 28 septembre 2026 03 h 38 EAT
*/

public final class LogHolder implements org.omg.CORBA.portable.Streamable
{
  public LogService.Log value = null;

  public LogHolder ()
  {
  }

  public LogHolder (LogService.Log initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = LogService.LogHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    LogService.LogHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return LogService.LogHelper.type ();
  }

}
